openapi: 3.0.3
info:
  title: 3GPP APIs
  description: HTTP messages and data types sent over 3GPP AS an VS APIs
  contact: {}
  version: '1.0'
servers:openapi: 3.0.3
info:
  title: 3GPP APIs
  description: HTTP messages and data types sent over 3GPP AS an VS APIs
  contact: {}
  version: '1.0'
servers:
  - url: http://localhost:8080/stir/v1
    description: 3GPP Endpoint
tags:
  - name: signing
    description: AS Endpoint
  - name: verification
    description: VS Endpoint
paths:
  /signing:
    post:
      tags:
        - signing
      summary: AS Request
      operationId: signingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/shakenSigningRequest'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/signingResponse'
        '400':
          description: Error in processing request 
          content:
            application/json:
              examples:
                missingRequestBody:
                  summary: Missing Request Body
                  value:
                    error: Missing request body
                missingMandatoryParameter:
                  summary: Missing Mandatory Parameter
                  value:
                    error: Missing Mandatory Parameter
                invalidParameterValue:
                  summary: Invalid Parameter Value
                  value:
                    error: Invalid Parameter Value
                failedToParseMessageBody:
                  summary: failedToParseMessageBody
                  value:
                    error: Failed To Parse Message Body
        '406':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Requested response body type is not supported
                    description: The request could not be processed due to a not supported message body format.
        '404':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Requested resource not found
                    description: The request could not be processed due to no resource available related to the Request-URI.
        '415':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Unsupported request body type
                    description: The request could not be processed due to not supported message body.
        '411':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Missing mandatory Content-Length headers
                    description: The request could not be processed due to a missing Content-Length header.
        '405':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Method not allowed
                    description: The resource was invoked with unsupported operation.
        '500':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Internal server error
                    description: The request failed due to internal error.
  /divSigning:
    post:
      tags:
        - divSigning
      summary: Diversion AS Request
      operationId: signingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/divSigningRequest'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/signingResponse'
        '400':
          description: Error in processing request 
          content:
            application/json:
              examples:
                missingRequestBody:
                  summary: Missing Request Body
                  value:
                    error: Missing request body
                missingMandatoryParameter:
                  summary: Missing Mandatory Parameter
                  value:
                    error: Missing Mandatory Parameter
                invalidParameterValue:
                  summary: Invalid Parameter Value
                  value:
                    error: Invalid Parameter Value
                failedToParseMessageBody:
                  summary: failedToParseMessageBody
                  value:
                    error: Failed To Parse Message Body
        '406':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Requested response body type is not supported
                    description: The request could not be processed due to a not supported message body format.
        '404':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Requested resource not found
                    description: The request could not be processed due to no resource available related to the Request-URI.
        '415':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Unsupported request body type
                    description: The request could not be processed due to not supported message body.
        '411':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Missing mandatory Content-Length headers
                    description: The request could not be processed due to a missing Content-Length header.
        '405':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Method not allowed
                    description: The resource was invoked with unsupported operation.
        '500':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Internal server error
                    description: The request failed due to internal error.
  /rphSigning:
    post:
      tags:
        - rphSigning
      summary: RPH AS Request
      operationId: signingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rphSigningRequest'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/signingResponse'
        '400':
          description: Error in processing request 
          content:
            application/json:
              examples:
                missingRequestBody:
                  summary: Missing Request Body
                  value:
                    error: Missing request body
                missingMandatoryParameter:
                  summary: Missing Mandatory Parameter
                  value:
                    error: Missing Mandatory Parameter
                invalidParameterValue:
                  summary: Invalid Parameter Value
                  value:
                    error: Invalid Parameter Value
                failedToParseMessageBody:
                  summary: failedToParseMessageBody
                  value:
                    error: Failed To Parse Message Body
        '406':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Requested response body type is not supported
                    description: The request could not be processed due to a not supported message body format.
        '404':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Requested resource not found
                    description: The request could not be processed due to no resource available related to the Request-URI.
        '415':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Unsupported request body type
                    description: The request could not be processed due to not supported message body.
        '411':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Missing mandatory Content-Length headers
                    description: The request could not be processed due to a missing Content-Length header.
        '405':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Method not allowed
                    description: The resource was invoked with unsupported operation.
        '500':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Internal server error
                    description: The request failed due to internal error.
components:
  schemas:
    shakenSigningRequest:
      title: signingRequest
      type: object
      required: 
        - attest
        - dest
        - iat
        - orig
        - origid
        - rph
        - sph
      properties:
        ppt:
          type: string
          example: shaken
          description: Optional field. If it's empty request is considered as "shaken" request. If "div", request is considered as "divSigning" request and if "rph", request is considered as "rphSigning" request
        attest: 
          type: string
          example: A , B or C
          description: Identifying the relation between the service provider attesting the identity and the subscriber. Specified in RFC 8588 [261]
        dest:
          type: array
          items:
            type: string
          description: Identifying the called user taken from the To header field for a shaken or rph PASSporT as specified in RFC 8224 [252], and from the Request-URI after retargeting for a div PASSporT as specified in RFC 8946 [265]
        div: 
          type: string
          description: Identifying the diverting user; i.e., the user identified in the Request-URI before retargeting, taken from the History-Info header field as specified in RFC 8946 [265]
        iat: 
          type: integer
          description: Time since 1 January 1970 in Numeric Date format as specified in RFC 7519 [235].
        orig: 
          type: string
          description: Identifying the calling user. Specified in RFC 8225 [262].
        origid: 
          type: string
          description: UUID Specified in RFC 8588 [261]
        rph: 
          type: array
          items:
            type: string
          description: Array of strings that correspond to the r-values indicated in the SIP Resource-Priority header field. Contains assertion of the priority level of the user to be used for a given communication session as specified in RFC 8443 [279] and RFC 9027 [278].
        sph: 
          type: string
          description: Contains header field value "psap-callback" of the SIP Priority header field as specified in RFC 9027 [278]
        hi: 
          type: string
          description: The "index" header field parameter is included in the entry identifying the diverting user in the History-Info header field.
        tn: 
          type: string
          description: allowed characters as for local-number-digits and global-number-digits defined in RFC 3966 [22]. The number needs to be in canonical form according to RFC 8224 [252]
        uri: 
          type: string
          description: A SIP URI as specified in RFC 3261 [26] following the generic guidelines in RFC. Used if the "orig" or "dest" is given in a SIP URI
    rphSigningRequest:
      title: signingRequest
      type: object
      required: 
        - dest
        - div
        - iat
        - orig
      properties:
        attest: 
          type: string
          example: A , B or C
          description: Identifying the relation between the service provider attesting the identity and the subscriber. Specified in RFC 8588 [261]
        dest:
          type: array
          items:
            type: string
          description: Identifying the called user taken from the To header field for a shaken or rph PASSporT as specified in RFC 8224 [252], and from the Request-URI after retargeting for a div PASSporT as specified in RFC 8946 [265]
        div: 
          type: string
          description: Identifying the diverting user; i.e., the user identified in the Request-URI before retargeting, taken from the History-Info header field as specified in RFC 8946 [265]
        iat: 
          type: integer
          description: Time since 1 January 1970 in Numeric Date format as specified in RFC 7519 [235].
        orig: 
          type: string
          description: Identifying the calling user. Specified in RFC 8225 [262].
        origid: 
          type: string
          description: UUID Specified in RFC 8588 [261]
        rph: 
          type: array
          items:
            type: string
          description: Array of strings that correspond to the r-values indicated in the SIP Resource-Priority header field. Contains assertion of the priority level of the user to be used for a given communication session as specified in RFC 8443 [279] and RFC 9027 [278].
        sph: 
          type: string
          description: Contains header field value "psap-callback" of the SIP Priority header field as specified in RFC 9027 [278]
        hi: 
          type: string
          description: The "index" header field parameter is included in the entry identifying the diverting user in the History-Info header field.
        tn: 
          type: string
          description: allowed characters as for local-number-digits and global-number-digits defined in RFC 3966 [22]. The number needs to be in canonical form according to RFC 8224 [252]
        uri: 
          type: string
          description: A SIP URI as specified in RFC 3261 [26] following the generic guidelines in RFC. Used if the "orig" or "dest" is given in a SIP URI
    divSigningRequest:
      title: signingRequest
      type: object
      required: 
        - dest
        - iat
        - orig
        - rph
      properties:
        attest: 
          type: string
          example: A , B or C
          description: Identifying the relation between the service provider attesting the identity and the subscriber. Specified in RFC 8588 [261]
        dest:
          type: array
          items:
            type: string
          description: Identifying the called user taken from the To header field for a shaken or rph PASSporT as specified in RFC 8224 [252], and from the Request-URI after retargeting for a div PASSporT as specified in RFC 8946 [265]
        div: 
          type: string
          description: Identifying the diverting user; i.e., the user identified in the Request-URI before retargeting, taken from the History-Info header field as specified in RFC 8946 [265]
        iat: 
          type: integer
          description: Time since 1 January 1970 in Numeric Date format as specified in RFC 7519 [235].
        orig: 
          type: string
          description: Identifying the calling user. Specified in RFC 8225 [262].
        origid: 
          type: string
          description: UUID Specified in RFC 8588 [261]
        rph: 
          type: array
          items:
            type: string
          description: Array of strings that correspond to the r-values indicated in the SIP Resource-Priority header field. Contains assertion of the priority level of the user to be used for a given communication session as specified in RFC 8443 [279] and RFC 9027 [278].
        sph: 
          type: string
          description: Contains header field value "psap-callback" of the SIP Priority header field as specified in RFC 9027 [278]
        hi: 
          type: string
          description: The "index" header field parameter is included in the entry identifying the diverting user in the History-Info header field.
        tn: 
          type: string
          description: allowed characters as for local-number-digits and global-number-digits defined in RFC 3966 [22]. The number needs to be in canonical form according to RFC 8224 [252]
        uri: 
          type: string
          description: A SIP URI as specified in RFC 3261 [26] following the generic guidelines in RFC. Used if the "orig" or "dest" is given in a SIP URI
    signingResponse:
      title: signingResponse
      type: object
      required: 
        - identityHeader
      properties:
        identityHeader:
          type: string
          description: Identity header field value as specified in RFC 8224 [252]. This string cannot be NULL
    errorResponse400a:
      title: errorResponseMissingRequestBody
      type: object
      required: 
        - error
      properties:
        error:
          type: string
          description: The request could not be processed due to missing request body.          
          example: Missing request body
    errorResponse400b:
      title: errorResponseMissingMandatoryParameter
      type: object
      required: 
        - error
      properties:
        error:
          type: string
          description: The request could not be processed due to missing parameters.
          example: Missing mandatory parameter
    errorResponse400c:
      title: errorResponseInvalidParameterValue
      type: object
      required: 
        - error
      properties:
        error:
          type: string
          description: The request could not be processed due to invalid parameter value.
          example: Invalid parameter value
    errorResponse400d:
      title: errorResponseFailedToParseMessageBody
      type: object
      required: 
        - error
      properties:
        error:
          type: string
          description: The request could not be processed due to failure to parse the message body
          example: Failed to parse message body
  - url: http://localhost:8080/stir/v1
    description: 3GPP Endpoint
tags:
  - name: signing
    description: AS Endpoint
  - name: verification
    description: VS Endpoint
paths:
  /signing:
    post:
      tags:
        - signing
      summary: AS Request
      operationId: signingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/shakenSigningRequest'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/signingResponse'
        '400':
          description: Error in processing request 
          content:
            application/json:
              examples:
                missingRequestBody:
                  summary: Missing Request Body
                  value:
                    error: Missing request body
                missingMandatoryParameter:
                  summary: Missing Mandatory Parameter
                  value:
                    error: Missing Mandatory Parameter
                invalidParameterValue:
                  summary: Invalid Parameter Value
                  value:
                    error: Invalid Parameter Value
                failedToParseMessageBody:
                  summary: failedToParseMessageBody
                  value:
                    error: Failed To Parse Message Body
        '406':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Requested response body type is not supported
                    description: The request could not be processed due to a not supported message body format.
        '404':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Requested resource not found
                    description: The request could not be processed due to no resource available related to the Request-URI.
        '415':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Unsupported request body type
                    description: The request could not be processed due to not supported message body.
        '411':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Missing mandatory Content-Length headers
                    description: The request could not be processed due to a missing Content-Length header.
        '405':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Method not allowed
                    description: The resource was invoked with unsupported operation.
        '500':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Internal server error
                    description: The request failed due to internal error.
  /divSigning:
    post:
      tags:
        - signing
      summary: Diversion AS Request
      operationId: divSigningPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/divSigningRequest'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/signingResponse'
        '400':
          description: Error in processing request 
          content:
            application/json:
              examples:
                missingRequestBody:
                  summary: Missing Request Body
                  value:
                    error: Missing request body
                missingMandatoryParameter:
                  summary: Missing Mandatory Parameter
                  value:
                    error: Missing Mandatory Parameter
                invalidParameterValue:
                  summary: Invalid Parameter Value
                  value:
                    error: Invalid Parameter Value
                failedToParseMessageBody:
                  summary: failedToParseMessageBody
                  value:
                    error: Failed To Parse Message Body
        '406':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Requested response body type is not supported
                    description: The request could not be processed due to a not supported message body format.
        '404':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Requested resource not found
                    description: The request could not be processed due to no resource available related to the Request-URI.
        '415':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Unsupported request body type
                    description: The request could not be processed due to not supported message body.
        '411':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Missing mandatory Content-Length headers
                    description: The request could not be processed due to a missing Content-Length header.
        '405':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Method not allowed
                    description: The resource was invoked with unsupported operation.
        '500':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Internal server error
                    description: The request failed due to internal error.
  /rphSigning:
    post:
      tags:
        - signing
      summary: RPH AS Request
      operationId: rphSigningPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rphSigningRequest'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/signingResponse'
        '400':
          description: Error in processing request 
          content:
            application/json:
              examples:
                missingRequestBody:
                  summary: Missing Request Body
                  value:
                    error: Missing request body
                missingMandatoryParameter:
                  summary: Missing Mandatory Parameter
                  value:
                    error: Missing Mandatory Parameter
                invalidParameterValue:
                  summary: Invalid Parameter Value
                  value:
                    error: Invalid Parameter Value
                failedToParseMessageBody:
                  summary: failedToParseMessageBody
                  value:
                    error: Failed To Parse Message Body
        '406':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Requested response body type is not supported
                    description: The request could not be processed due to a not supported message body format.
        '404':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Requested resource not found
                    description: The request could not be processed due to no resource available related to the Request-URI.
        '415':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Unsupported request body type
                    description: The request could not be processed due to not supported message body.
        '411':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Missing mandatory Content-Length headers
                    description: The request could not be processed due to a missing Content-Length header.
        '405':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Method not allowed
                    description: The resource was invoked with unsupported operation.
        '500':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Internal server error
                    description: The request failed due to internal error.
components:
  schemas:
    shakenSigningRequest:
      title: signingRequest
      type: object
      required: 
        - attest
        - dest
        - iat
        - orig
        - origid
        - rph
        - sph
      properties:
        ppt:
          type: string
          example: shaken
          description: Optional field. If it's empty request is considered as "shaken" request. If "div", request is considered as "divSigning" request and if "rph", request is considered as "rphSigning" request
        attest: 
          type: string
          example: A , B or C
          description: Identifying the relation between the service provider attesting the identity and the subscriber. Specified in RFC 8588 [261]
        dest:
          type: array
          items:
            type: string
          description: Identifying the called user taken from the To header field for a shaken or rph PASSporT as specified in RFC 8224 [252], and from the Request-URI after retargeting for a div PASSporT as specified in RFC 8946 [265]
        div: 
          type: string
          description: Identifying the diverting user; i.e., the user identified in the Request-URI before retargeting, taken from the History-Info header field as specified in RFC 8946 [265]
        iat: 
          type: integer
          description: Time since 1 January 1970 in Numeric Date format as specified in RFC 7519 [235].
        orig: 
          type: string
          description: Identifying the calling user. Specified in RFC 8225 [262].
        origid: 
          type: string
          description: UUID Specified in RFC 8588 [261]
        rph: 
          type: array
          items:
            type: string
          description: Array of strings that correspond to the r-values indicated in the SIP Resource-Priority header field. Contains assertion of the priority level of the user to be used for a given communication session as specified in RFC 8443 [279] and RFC 9027 [278].
        sph: 
          type: string
          description: Contains header field value "psap-callback" of the SIP Priority header field as specified in RFC 9027 [278]
        hi: 
          type: string
          description: The "index" header field parameter is included in the entry identifying the diverting user in the History-Info header field.
        tn: 
          type: string
          description: allowed characters as for local-number-digits and global-number-digits defined in RFC 3966 [22]. The number needs to be in canonical form according to RFC 8224 [252]
        uri: 
          type: string
          description: A SIP URI as specified in RFC 3261 [26] following the generic guidelines in RFC. Used if the "orig" or "dest" is given in a SIP URI
    rphSigningRequest:
      title: signingRequest
      type: object
      required: 
        - dest
        - div
        - iat
        - orig
      properties:
        attest: 
          type: string
          example: A , B or C
          description: Identifying the relation between the service provider attesting the identity and the subscriber. Specified in RFC 8588 [261]
        dest:
          type: array
          items:
            type: string
          description: Identifying the called user taken from the To header field for a shaken or rph PASSporT as specified in RFC 8224 [252], and from the Request-URI after retargeting for a div PASSporT as specified in RFC 8946 [265]
        div: 
          type: string
          description: Identifying the diverting user; i.e., the user identified in the Request-URI before retargeting, taken from the History-Info header field as specified in RFC 8946 [265]
        iat: 
          type: integer
          description: Time since 1 January 1970 in Numeric Date format as specified in RFC 7519 [235].
        orig: 
          type: string
          description: Identifying the calling user. Specified in RFC 8225 [262].
        origid: 
          type: string
          description: UUID Specified in RFC 8588 [261]
        rph: 
          type: array
          items:
            type: string
          description: Array of strings that correspond to the r-values indicated in the SIP Resource-Priority header field. Contains assertion of the priority level of the user to be used for a given communication session as specified in RFC 8443 [279] and RFC 9027 [278].
        sph: 
          type: string
          description: Contains header field value "psap-callback" of the SIP Priority header field as specified in RFC 9027 [278]
        hi: 
          type: string
          description: The "index" header field parameter is included in the entry identifying the diverting user in the History-Info header field.
        tn: 
          type: string
          description: allowed characters as for local-number-digits and global-number-digits defined in RFC 3966 [22]. The number needs to be in canonical form according to RFC 8224 [252]
        uri: 
          type: string
          description: A SIP URI as specified in RFC 3261 [26] following the generic guidelines in RFC. Used if the "orig" or "dest" is given in a SIP URI
    divSigningRequest:
      title: signingRequest
      type: object
      required: 
        - dest
        - iat
        - orig
        - rph
      properties:
        attest: 
          type: string
          example: A , B or C
          description: Identifying the relation between the service provider attesting the identity and the subscriber. Specified in RFC 8588 [261]
        dest:
          type: array
          items:
            type: string
          description: Identifying the called user taken from the To header field for a shaken or rph PASSporT as specified in RFC 8224 [252], and from the Request-URI after retargeting for a div PASSporT as specified in RFC 8946 [265]
        div: 
          type: string
          description: Identifying the diverting user; i.e., the user identified in the Request-URI before retargeting, taken from the History-Info header field as specified in RFC 8946 [265]
        iat: 
          type: integer
          description: Time since 1 January 1970 in Numeric Date format as specified in RFC 7519 [235].
        orig: 
          type: string
          description: Identifying the calling user. Specified in RFC 8225 [262].
        origid: 
          type: string
          description: UUID Specified in RFC 8588 [261]
        rph: 
          type: array
          items:
            type: string
          description: Array of strings that correspond to the r-values indicated in the SIP Resource-Priority header field. Contains assertion of the priority level of the user to be used for a given communication session as specified in RFC 8443 [279] and RFC 9027 [278].
        sph: 
          type: string
          description: Contains header field value "psap-callback" of the SIP Priority header field as specified in RFC 9027 [278]
        hi: 
          type: string
          description: The "index" header field parameter is included in the entry identifying the diverting user in the History-Info header field.
        tn: 
          type: string
          description: allowed characters as for local-number-digits and global-number-digits defined in RFC 3966 [22]. The number needs to be in canonical form according to RFC 8224 [252]
        uri: 
          type: string
          description: A SIP URI as specified in RFC 3261 [26] following the generic guidelines in RFC. Used if the "orig" or "dest" is given in a SIP URI
    signingResponse:
      title: signingResponse
      type: object
      required: 
        - identityHeader
      properties:
        identityHeader:
          type: string
          description: Identity header field value as specified in RFC 8224 [252]. This string cannot be NULL
    errorResponse400a:
      title: errorResponseMissingRequestBody
      type: object
      required: 
        - error
      properties:
        error:
          type: string
          description: The request could not be processed due to missing request body.          
          example: Missing request body
    errorResponse400b:
      title: errorResponseMissingMandatoryParameter
      type: object
      required: 
        - error
      properties:
        error:
          type: string
          description: The request could not be processed due to missing parameters.
          example: Missing mandatory parameter
    errorResponse400c:
      title: errorResponseInvalidParameterValue
      type: object
      required: 
        - error
      properties:
        error:
          type: string
          description: The request could not be processed due to invalid parameter value.
          example: Invalid parameter value
    errorResponse400d:
      title: errorResponseFailedToParseMessageBody
      type: object
      required: 
        - error
      properties:
        error:
          type: string
          description: The request could not be processed due to failure to parse the message body
          example: Failed to parse message body
